from Tkinter import *
master=Tk()
Label(master,text='First').grid(row=0)
Label(master,text="Second").grid(row=1)
Label(master,text="Third").grid(row=2,sticky=W)
Label(master,text="Fourth").grid(row=3,sticky=W)
e1=Entry(master)
e2=Entry(master)
e3=Entry(master)
e4=Entry(master)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e2.grid(row=2,column=1)
e2.grid(row=3,column=1)
mainloop()