from Tkinter import *
root=Tk()
Button(root,text="1").grid(row=0,column=0)
Button(root,text="2").grid(row=0,column=1)
Button(root,text="3").grid(row=0,column=2)
Button(root,text="4").grid(row=1,column=0)
Button(root,text="5").grid(row=1,column=1)
Button(root,text="6").grid(row=1,column=2)
Button(root,text="7").grid(row=2,column=0)
Button(root,text="8").grid(row=2,column=1)
Button(root,text="9").grid(row=2,column=2)
Button(root,text="0").grid(row=3,column=0,columnspan=2,sticky=E+W)
Button(root,text=".").grid(row=3,column=2,sticky=E+W)
root.mainloop()
